const C = @import("sdl2-c-binding.zig");

pub extern fn IMG_Linked_Version() [*c]const C.SDL_version;
pub const IMG_INIT_JPG: c_int = 1;
pub const IMG_INIT_PNG: c_int = 2;
pub const IMG_INIT_TIF: c_int = 4;
pub const IMG_INIT_WEBP: c_int = 8;
pub const IMG_InitFlags = c_uint;
pub extern fn IMG_Init(flags: c_int) c_int;
pub extern fn IMG_Quit() void;
pub extern fn IMG_LoadTyped_RW(src: [*c]C.SDL_RWops, freesrc: c_int, @"type": [*c]const u8) [*c]C.SDL_Surface;
pub extern fn IMG_Load(file: [*c]const u8) [*c]C.SDL_Surface;
pub extern fn IMG_Load_RW(src: [*c]C.SDL_RWops, freesrc: c_int) [*c]C.SDL_Surface;
pub extern fn IMG_LoadTexture(renderer: ?*C.SDL_Renderer, file: [*c]const u8) ?*C.SDL_Texture;
pub extern fn IMG_LoadTexture_RW(renderer: ?*C.SDL_Renderer, src: [*c]C.SDL_RWops, freesrc: c_int) ?*C.SDL_Texture;
pub extern fn IMG_LoadTextureTyped_RW(renderer: ?*C.SDL_Renderer, src: [*c]C.SDL_RWops, freesrc: c_int, @"type": [*c]const u8) ?*C.SDL_Texture;
pub extern fn IMG_isICO(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isCUR(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isBMP(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isGIF(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isJPG(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isLBM(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isPCX(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isPNG(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isPNM(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isSVG(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isTIF(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isXCF(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isXPM(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isXV(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_isWEBP(src: [*c]C.SDL_RWops) c_int;
pub extern fn IMG_LoadICO_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadCUR_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadBMP_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadGIF_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadJPG_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadLBM_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadPCX_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadPNG_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadPNM_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadSVG_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadTGA_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadTIF_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadXCF_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadXPM_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadXV_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_LoadWEBP_RW(src: [*c]C.SDL_RWops) [*c]C.SDL_Surface;
pub extern fn IMG_ReadXPMFromArray(xpm: [*c][*c]u8) [*c]C.SDL_Surface;
pub extern fn IMG_SavePNG(surface: [*c]C.SDL_Surface, file: [*c]const u8) c_int;
pub extern fn IMG_SavePNG_RW(surface: [*c]C.SDL_Surface, dst: [*c]C.SDL_RWops, freedst: c_int) c_int;
pub extern fn IMG_SaveJPG(surface: [*c]C.SDL_Surface, file: [*c]const u8, quality: c_int) c_int;
pub extern fn IMG_SaveJPG_RW(surface: [*c]C.SDL_Surface, dst: [*c]C.SDL_RWops, freedst: c_int, quality: c_int) c_int;
